### ISSUE TITLE
not working with python script

### ISSUE THREAD

**Issue by ManuelW77** [Salandora/octoprint-customControl#10]
Hey there,

i try to execute a python script and set a script command with "/home/pi/camcran.py up".
Same i use in system command editor and it works fine there. 
But in custom control nothing happens.

**Comment by Salandora** [comment]
Well thats because the customControls don't systemcommands ^^
Script commands is for this: http://docs.octoprint.org/en/master/features/custom_controls.html#parameterized-gcode-script
http://docs.octoprint.org/en/master/features/gcode_scripts.html#sec-features-gcode-scripts

Also just a note: 
This is just an editor plugin, it's only purpose is to give an easy way to manage custom controls, which is a core feature of OctoPrint.
